---
# better to have realtime clock in utc
- name: detect local rtc
  shell: "timedatectl | grep -oP '(?<=RTC in local TZ: )(yes|no)'"
  register: local_rtc_output
  changed_when: false

- name: disable local rtc
  command: timedatectl set-local-rtc false
  when: local_rtc_output.get('rc') == 0 and (local_rtc_output.stdout|trim) == "yes"

# make sure that systemd takes advantage of network time
- name: detect network time status
  shell: "timedatectl | grep -oP '(?<=NTP synchronized: )(yes|no)'"
  register: ntp_synchronized_output
  changed_when: false

- name: enable network time
  command: timedatectl set-ntp true
  when: ntp_synchronized_output.get('rc') == 0 and (ntp_synchronized_output|trim) == "yes"
